import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import stasis from '@/components/assets/stasis.jpg'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Stasis Artis",
  description: "Generated by create next app",
  icons: {
    icon: stasis.src,
    apple: stasis.src,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
